language: node_js
node_js:
  - '10'
  - '8'
  - '6'
before_script:
  - npm install babel-cli
  - npm install babel-core
  - npm install babel-register
  - npm install -g mocha
  - npm install -g eslint
script:
  - npm run lint
  - npm test
  - npm run build
